services:
  apache:
    image: httpd:2.4
    container_name: apache_server
    ports:
      - "8080:80"
    volumes:
      - .:/usr/local/apache2/htdocs/
      - ./httpd.conf:/usr/local/apache2/httpd.conf
    restart: always